# This is my basic workflow of Actions

name: Jake A.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
- [ ] On paper, I will use a shift cipher to encrypt and decrypt a short message to get a feel for how this cipher works.
- [ ] Highlight how I will use conditionals and flow controls to convert a string into a number.
- [ ] Brush up my knowledge on how I will implement my knowledge of strings, arrays, and hashes for encrypting and decrypting messages.
- [ ] Develop an algorithm for this procedure that works for input text and shift value.
- [ ] Create and initialize (set to blank) three variables to store inputText, shiftValue, and outputText.
- [ ] Ask the user to enter a plaintext message to be encoded. 
- [ ] Set the inputText variable to the answer from the user.
- [ ] Ask the user to enter a shift value for the shift cipher. If their answer is a number; Set the shiftValue variable to their answer.
- [ ] Ask the user if they wish to encode or decode.
- [ ] Then call a custom procedure to encrypt or decrypt the data. 
- [ ] Check that my code works as expected.
- [ ] Ensure my code wraps from z to a and keeps the same case.
- [ ] Adding the Brute Force Mode to my code 
- [ ] Package my code as a chrome extension
- [ ] Create and add a Manifest.json file to my code
- [ ] Use a google developer account to upload my project to the Chrome extension store - https://www.freecodecamp.org/news/building-chrome-extension/ 
- [ ] Publish my project to the chrome web store for other cybersecurity enthusiasts to test, use and play with  - https://developer.chrome.com/docs/webstore/register/ 


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
